name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Type Check
        run: npm run typecheck

      - name: Run Tests
        run: npm run test

      - name: Clean
        run: npm run clean

      - name: Build All Packages
        run: npm run build:all

      - name: Verify CDN Build
        run: |
          if [ ! -d "cdn" ]; then
            echo "CDN build failed - directory missing"
            exit 1
          fi

      - name: Verify Dist Build
        run: |
          if [ ! -d "dist" ]; then
            echo "Dist build failed - directory missing"
            exit 1
          fi

  version-check:
    needs: validate
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check Package Version
        id: version_check
        run: |
          BASE_VERSION=$(git show origin/main:package.json | jq -r .version)
          CURRENT_VERSION=$(jq -r .version package.json)
          if [ "$BASE_VERSION" = "$CURRENT_VERSION" ] && [ "${{ contains(github.event.pull_request.labels.*.name, 'no-version-bump') }}" != "true" ]; then
            echo "Error: Version must be bumped in package.json unless PR is labeled with 'no-version-bump'"
            exit 1
          fi
